张量的创建：

1.创建一个张量：------------------------------------torch.tensor()

2.创建稀疏张量：------------------------------------torch.sparse_coo_tensor()

3.将数据转换成张量：--------------------------------torch.as_tensor()

4.从numpy.ndarray创建一个张量：---------------------torch.from_numpy(ndarray) 

5.创建元素值为0的张量:------------------------------torch.zeros()

6.创建一个和input相同大小的，元素值为0的张量：------torch.zeros_like()

7.创建一个全1张量：---------------------------------torch.ones()

8.创建一个与input相同大小的全1张量：----------------torch.ones_like()

9.创建一个一维序列张量：----------------------------torch.arange()

10.创建一个等距（相同步长）的一维张量：-------------torch.linspace()

11.创建一个指数值结果的一维张量 ：------------------torch.logspace()

12.创建一个对角线值为1，其它为0的张量：-------------torch.eye()

13.创建一个未初始化的张量：-------------------------torch.empty()

14.创建一个和input维度相同的未初始化张量：----------torch.empty_like()

15.创建由某个数值填充的张量：-----------------------torch.full()

16.创建一个维度和input一样的由某个值填充的张量：----torch.full_like()


备注：来源于pytorch官方文档：https://pytorch.org/docs/stable/torch.html#tensors

这里张量就是torch.tensor

In [ ]:
1.torch.tensor(data, dtype=None, device=None, requires_grad=False) → Tensor

data:用来初始化的数据. 可以是 a list, tuple, NumPy ndarray, scalar, and other types.
dtype：数据类型，None则继承data的类型
device：返回张量的设备‘cuda’，‘cpu’
requires_grad：自动记录，计算该变量梯度

In [4]:
import torch

torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, 5.2]])


tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [5]:
torch.tensor([0, 1])  # Type inference on data


tensor([0, 1])

In [6]:
torch.tensor(3.14159)  # Create a scalar (zero-dimensional tensor)


tensor(3.1416)

In [7]:
torch.tensor([])  # Create an empty tensor (of size (0,))

tensor([])

In [ ]:
torch.tensor([[0.11111, 0.222222, 0.3333333]],
                 dtype=torch.float64,
                 device=torch.device('cuda:0'))  # creates a torch.cuda.DoubleTensor

In [ ]:
2.创建稀疏张量：torch.sparse_coo_tensor(indices, values, size=None, dtype=None, device=None, requires_grad=False) → Tensor

indices：非0元素的索引值，可以是列表、元组、NumPy ndarray、标量和其他类型。
value:可以是列表、元组、NumPy ndarray、标量和其他类型。
size:稀疏张量的大小，没定义的话将自动匹配能容纳所有元素的最小尺寸。
dtype：数据类型，没定义的话继承values的数据类型。


In [10]:
i = torch.tensor([[0, 1, 1],
                      [2, 0, 2]])
v = torch.tensor([3, 4, 5], dtype=torch.float32)
torch.sparse_coo_tensor(i, v, [2, 4])

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3., 4., 5.]),
       size=(2, 4), nnz=3, layout=torch.sparse_coo)

In [11]:
torch.sparse_coo_tensor(i, v)

tensor(indices=tensor([[0, 1, 1],
                       [2, 0, 2]]),
       values=tensor([3., 4., 5.]),
       size=(2, 3), nnz=3, layout=torch.sparse_coo)

In [ ]:
torch.sparse_coo_tensor(i, v, [2, 4],
                            dtype=torch.float64,
                            device=torch.device('cuda:0'))

In [ ]:
# Create an empty sparse tensor with the following invariants:
#   1. sparse_dim + dense_dim = len(SparseTensor.shape)
#   2. SparseTensor._indices().shape = (sparse_dim, nnz)
#   3. SparseTensor._values().shape = (nnz, SparseTensor.shape[sparse_dim:])
#
# For instance, to create an empty sparse tensor with nnz = 0, dense_dim = 0 and
# sparse_dim = 1 (hence indices is a 2D tensor of shape = (1, 0))


In [14]:
S = torch.sparse_coo_tensor(torch.empty([1, 0]), [], [1])
S

tensor(indices=tensor([], size=(1, 0)),
       values=tensor([], size=(0,)),
       size=(1,), nnz=0, layout=torch.sparse_coo)

In [ ]:
# and to create an empty sparse tensor with nnz = 0, dense_dim = 1 and
# sparse_dim = 1

In [15]:
S = torch.sparse_coo_tensor(torch.empty([1, 0]), torch.empty([0, 2]), [1, 2])
S

tensor(indices=tensor([], size=(1, 0)),
       values=tensor([], size=(0, 2)),
       size=(1, 2), nnz=0, layout=torch.sparse_coo)

In [ ]:
3. 将数据转换成torch.tensor:torch.as_tensor(data, dtype=None, device=None) → Tensor
    
    data:可以是列表、元组、NumPy ndarray、标量和其他类型。

In [17]:
import numpy

a = numpy.array([1, 2, 3])
t = torch.as_tensor(a)
t

tensor([1, 2, 3], dtype=torch.int32)

In [18]:
t[0] = -1
t

tensor([-1,  2,  3], dtype=torch.int32)

In [ ]:
a = numpy.array([1, 2, 3])
t = torch.as_tensor(a, device=torch.device('cuda'))
t

In [ ]:
4. 从numpy.ndarray创建一个tensor：torch.from_numpy(ndarray) → Tensor  

二者共享内存，所以一个变化，两个都变

In [20]:
a = numpy.array([1, 2, 3])
t = torch.from_numpy(a)
t

tensor([1, 2, 3], dtype=torch.int32)

In [21]:
t[0] = -1
a

array([-1,  2,  3])

In [ ]:
5. 创建元素值为0的张量:torch.zeros(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
    
    sizes:列表或元祖，张量大小

In [28]:
torch.zeros(1, 3)


tensor([[0., 0., 0.]])

In [29]:
torch.zeros(5)

tensor([0., 0., 0., 0., 0.])

In [ ]:
6.创建一个和input相同大小的，元素值为0的张量：torch.zeros_like(input, dtype=None, layout=None, device=None, requires_grad=False) → Tensor


In [51]:
input = torch.empty(2, 3)
torch.zeros_like(input)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

7.创建一个全1张量：torch.ones(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor


In [31]:
torch.ones(2, 3)


tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [32]:
torch.ones(5)

tensor([1., 1., 1., 1., 1.])

8.创建一个与input相同大小的全1张量：torch.ones_like(input, dtype=None, layout=None, device=None, requires_grad=False) → Tensor

In [33]:
input = torch.empty(2, 3)
torch.ones_like(input)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

9. 创建一个一维序列张量：torch.arange(start=0, end, step=1, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
start：开始的数，默认为0
end：结束的数
step：步长，默认为1


In [34]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [35]:
torch.arange(1, 4)

tensor([1, 2, 3])

In [36]:
torch.arange(1, 2.5, 0.5)

tensor([1.0000, 1.5000, 2.0000])

10.创建一个等距（相同步长）的一维张量：torch.linspace(start, end, steps=100, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

steps：元素数目

In [37]:
torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [38]:
torch.linspace(-10, 10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

In [39]:
torch.linspace(start=-10, end=10, steps=5)

tensor([-10.,  -5.,   0.,   5.,  10.])

11. 创建一个指数值结果的一维张量 ：torch.logspace(start, end, steps=100, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

例如$10^{\text{start}}
  到 10^{\text{end}}$

In [41]:
torch.logspace(start=-10, end=10, steps=5)

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [42]:
torch.logspace(start=0.1, end=1.0, steps=5)

tensor([ 1.2589,  2.1135,  3.5481,  5.9566, 10.0000])

12. 创建一个对角线值为1，其它为0的张量：torch.eye(n, m=None, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

m:列数，默认=n

In [43]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

13.创建一个未初始化的张量：torch.empty(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

In [44]:
torch.empty(2, 3)

tensor([[-9.5625e-14,  4.5907e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

14.创建一个和input维度相同的未初始化张量：torch.empty_like(input, dtype=None, layout=None, device=None, requires_grad=False) → Tensor

In [47]:
aa = torch.empty((2,3), dtype=torch.int64)
torch.empty_like(aa)

tensor([[0, 0, 0],
        [0, 0, 0]])

15.创建由某个数值填充的张量：torch.full(size, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

fill_value:用来填充的数

In [48]:
torch.full((2, 3), 3.141592)

tensor([[3.1416, 3.1416, 3.1416],
        [3.1416, 3.1416, 3.1416]])

16.创建一个维度和input一样的由某个值填充的张量：torch.full_like(input, fill_value, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor