torch 随机数，随机采样：  

1.设置随机种子seed：------------------------------------torch.manual_seed(seed)  

2.返回随机数种子：--------------------------------------torch.initial_seed()

3.从伯努利分布中抽取二进制随机数(0或1)：----------------torch.bernoulli()

4.按概率取随机数：--------------------------------------torch.multinomial()

5.正态分布取随机数：------------------------------------torch.normal()

6.取[0,1)之间的随机数（平均分布）：---------------------torch.rand()

7.固定tensor维度，取[0,1)之间的随机数（平均分布）：-----torch.rand_like()

8.取整数随机数（平均分布）：----------------------------torch.randint()

9.固定大小取整数随机数（平均分布）：--------------------torch.randint_like()

10.均值为0，方差为1正态分布的随机数：-------------------torch.randn()

11.固定大小，均值为0，方差为1正态分布的随机数：---------torch.randn_like()

12.返回从0到n - 1整数的随机排列：-----------------------torch.randperm()

In [1]:
import torch

1.设置随机种子seed：torch.manual_seed(seed)

2.返回随机数种子：torch.initial_seed()

In [2]:
torch.initial_seed()

1555570897

3.从伯努利分布中抽取二进制随机数(0或1)：torch.bernoulli(input, *, generator=None, out=None) → Tensor    
input：输入值的范围在[0,1]，计算伯努利分布概率，输出0或1


In [3]:
a = torch.empty(3, 3).uniform_(0, 1)  # generate a uniform random matrix with range [0, 1]
a

tensor([[0.7614, 0.7513, 0.0680],
        [0.6001, 0.1666, 0.7379],
        [0.5320, 0.3465, 0.0304]])

In [4]:
torch.bernoulli(a)

tensor([[1., 1., 0.],
        [1., 0., 1.],
        [0., 1., 0.]])

In [5]:
a = torch.ones(3, 3) # probability of drawing "1" is 1
torch.bernoulli(a)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
a = torch.zeros(3, 3) # probability of drawing "1" is 0
torch.bernoulli(a)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

4.按概率取随机数：torch.multinomial(input, num_samples, replacement=False, out=None) → LongTensor  
input：是一个概率的权重（非零值），值越大取这个值索引的概率越大，输出是所取值的索引    
num_samples：是取值的次数，若replacement=False（就是不放回取，只能取一次）次数不能大于元素值大于0的元素个数  
如果input是一个向量，则输出是一个num_samples维的向量。  
如果input是一个m行的矩阵，输出是m×num_samples大小。  


In [10]:
weights = torch.tensor([0, 10, 3, 0], dtype=torch.float) # create a tensor of weights
torch.multinomial(weights, 2)

tensor([1, 2])

In [14]:
torch.multinomial(weights, 10, replacement=True)

tensor([1, 1, 1, 2, 1, 1, 1, 1, 1, 1])

5.正态分布取随机数：torch.normal(mean, std, out=None) → Tensor  
mean：均值  
std：标准差  


In [15]:
torch.normal(mean=torch.arange(1., 11.), std=torch.arange(1, 0, -0.1))

tensor([ 0.7451,  3.4448,  3.1756,  3.6106,  5.8676,  6.5840,  6.5986,  7.9055,
         9.1784, 10.0233])

In [16]:
#torch.normal(mean=0.0, std, out=None) → Tensor
torch.normal(mean=0.5, std=torch.arange(1., 6.))#共享均值

tensor([-0.8370,  2.1654,  0.3218,  8.3141, -2.6650])

In [17]:
#torch.normal(mean, std=1.0, out=None) → Tensor
torch.normal(mean=torch.arange(1., 6.))#共享标准差

tensor([1.8423, 1.6108, 4.5549, 2.6787, 5.3668])

6.取[0,1)之间的随机数（平均分布）：torch.rand(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor  
    size：tensor的形状大小（维度）  
    

In [18]:
torch.rand(4)

tensor([0.0975, 0.4187, 0.0866, 0.7606])

In [19]:
torch.rand(2, 3)

tensor([[0.8270, 0.8854, 0.4815],
        [0.1208, 0.2513, 0.6978]])

7.固定tensor维度，取[0,1)之间的随机数（平均分布）：torch.rand_like(input, dtype=None, layout=None, device=None, requires_grad=False) → Tensor  
               输出形状与input大小一样。

8.取整数随机数（平均分布）：torch.randint(low=0, high, size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor  
取low和high之间的整数（不包括low和high）。

In [21]:
torch.randint(3, 5, (3,))

tensor([4, 3, 3])

In [23]:
torch.randint(10, (2, 2))

tensor([[7, 3],
        [9, 9]])

In [26]:
torch.randint(3, 10, (2, 2))

tensor([[4, 5],
        [4, 5]])

9.固定大小取整数随机数（平均分布）：torch.randint_like(input, low=0, high, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor

10.均值为0，方差为1正态分布的随机数：torch.randn(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor  


In [27]:
torch.randn(4)

tensor([ 1.3092, -2.8188,  0.9212, -0.4268])

In [28]:
torch.randn(2, 3)

tensor([[-0.5284,  0.5985, -0.1372],
        [-0.6728, -0.1836, -0.1727]])

11.固定大小，均值为0，方差为1正态分布的随机数：torch.randn_like(input, dtype=None, layout=None, device=None, requires_grad=False) → Tensor  


12.返回从0到n - 1整数的随机排列：torch.randperm(n, out=None, dtype=torch.int64, layout=torch.strided, device=None, requires_grad=False) → LongTensor  
n：上界  


In [30]:
torch.randperm(4)

tensor([1, 3, 0, 2])