张量的索引，切片，连接，更改：  

1.连接张量：------------------------------------torch.cat()
2.分割特定数目的张量：--------------------------torch.chunk()

3.按特定维度和索引取值：------------------------torch.gather()

4.按索引取整行、整列：--------------------------torch.index_select()

5.根据掩码（mask）取元素：----------------------torch.masked_select()

6.缩小张量：------------------------------------torch.narrow()

7.取非零元素的索引：----------------------------torch.nonzero()

8.reshape张量：---------------------------------torch.reshape()

9.分割矩阵：------------------------------------torch.split()

10.去除维度为1的维度：--------------------------torch.squeeze()

11.连接张量：-----------------------------------torch.stack()

12.转置：---------------------------------------torch.t(input)

13.取出指定位置元素：---------------------------torch.take()

14.转置：---------------------------------------torch.transpose()

15.将tensor切片成元组：-------------------------torch.unbind()

16.增加维度：-----------------------------------torch.unsqueeze() 

17.按条件从两个tensor中挑选元素组成新tensor：---torch.where()

In [2]:
import torch

1.连接张量：torch.cat(tensors, dim=0, out=None) → Tensor  
张量的维度必须相同  
dim:在哪个维度上连接

In [3]:
x = torch.randn(2, 3)
x

tensor([[ 0.2699,  1.1784, -0.1974],
        [ 0.1379,  0.2558,  0.7817]])

In [4]:
torch.cat((x, x, x), 0)

tensor([[ 0.2699,  1.1784, -0.1974],
        [ 0.1379,  0.2558,  0.7817],
        [ 0.2699,  1.1784, -0.1974],
        [ 0.1379,  0.2558,  0.7817],
        [ 0.2699,  1.1784, -0.1974],
        [ 0.1379,  0.2558,  0.7817]])

In [5]:
torch.cat((x, x, x), 1)

tensor([[ 0.2699,  1.1784, -0.1974,  0.2699,  1.1784, -0.1974,  0.2699,  1.1784,
         -0.1974],
        [ 0.1379,  0.2558,  0.7817,  0.1379,  0.2558,  0.7817,  0.1379,  0.2558,
          0.7817]])

2.分割特定数目的张量：torch.chunk(tensor, chunks, dim=0) → List of Tensors  
chunks：分割的数目

In [6]:
a = torch.randn(5, 6)
torch.chunk(a, 2, dim=0)

(tensor([[ 2.1673, -0.8886,  0.8499, -0.8105, -0.5820, -0.5908],
         [-0.2695, -1.1172, -0.2423, -1.3921,  0.6245, -0.1917],
         [-0.0477, -0.0491, -0.1908, -0.4689, -0.7814, -0.4261]]),
 tensor([[-1.6854,  1.0078,  0.1544,  0.0204,  0.9406,  0.5258],
         [ 0.7861,  0.0200,  0.7481, -0.7727, -1.6728, -0.5807]]))

In [7]:
t = torch.tensor([[1,2],[3,4]])
torch.gather(t, 1, torch.tensor([[0,0],[1,0]]))

tensor([[1, 1],
        [4, 3]])

3.按特定维度和索引取值：torch.gather(input, dim, index, out=None) → Tensor  
dim：选取的维度  
index：在该维度下的缩影位置  

三维数据取法：  
out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0  
out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1  
out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2  

In [14]:
t = torch.tensor([[1,2],[3,4]])
torch.gather(t, 1, torch.tensor([[0,0],[1,0]]))#1：按行取，[0,0]：第一行的索引0的值，第一行的索引0的值，[1,0]:第二行索引1的值，第二行索引0的值  



tensor([[1, 1],
        [4, 3]])

In [10]:
a = torch.randn(2,2,2)
a

tensor([[[-0.4354, -0.2510],
         [-0.1239, -0.6626]],

        [[-0.5580,  0.3644],
         [-2.0567, -0.0738]]])

In [11]:
torch.gather(a,0,torch.tensor([[[0,0],[0,1]],[[0,0],[1,0]]]))

tensor([[[-0.4354, -0.2510],
         [-0.1239, -0.0738]],

        [[-0.4354, -0.2510],
         [-2.0567, -0.6626]]])

In [12]:
a

tensor([[[-0.4354, -0.2510],
         [-0.1239, -0.6626]],

        [[-0.5580,  0.3644],
         [-2.0567, -0.0738]]])

4.按索引取整行、整列：torch.index_select(input, dim, index, out=None) → Tensor  
index：一维索引张量

In [3]:
x = torch.randn(3, 4)
x

tensor([[ 1.6252, -0.2069, -0.4375, -0.2583],
        [ 0.9916, -0.2663,  0.1913, -0.7262],
        [-0.6162,  0.5308,  0.4643,  0.9128]])

In [7]:
indices = torch.tensor([0, 2, 0])
torch.index_select(x, 0, indices)#按行取第0行，第2行，第0行

tensor([[ 1.6252, -0.2069, -0.4375, -0.2583],
        [-0.6162,  0.5308,  0.4643,  0.9128],
        [ 1.6252, -0.2069, -0.4375, -0.2583]])

In [8]:
torch.index_select(x, 1, indices)

tensor([[ 1.6252, -0.4375,  1.6252],
        [ 0.9916,  0.1913,  0.9916],
        [-0.6162,  0.4643, -0.6162]])

5.根据掩码（mask）取元素：torch.masked_select(input, mask, out=None) → Tensor  
mask的shape不需要和input相同，但数目要相同

In [14]:
x = torch.randn(3, 4)
x

tensor([[ 0.3555, -2.4503, -0.5795,  0.8988],
        [ 1.3409,  0.6143, -0.0377,  0.0620],
        [ 0.6315,  0.9311,  0.1348,  0.8666]])

In [15]:
mask = x.ge(0.5)
mask

tensor([[0, 0, 0, 1],
        [1, 1, 0, 0],
        [1, 1, 0, 1]], dtype=torch.uint8)

In [16]:
torch.masked_select(x, mask) #取出mask值为1的位置的元素

tensor([0.8988, 1.3409, 0.6143, 0.6315, 0.9311, 0.8666])

6.缩小张量：torch.narrow(input, dimension, start, length) → Tensor  
start：开始取得起始位置  
length：要取的数目，长度

In [17]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
torch.narrow(x, 0, 0, 2)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [20]:
a = torch.narrow(x, 1, 1, 2)
a

tensor([[2, 3],
        [5, 6],
        [8, 9]])

In [21]:
a[0][0] = 1  #共享内存，取出的tensor变，原input也变
x

tensor([[1, 1, 3],
        [4, 5, 6],
        [7, 8, 9]])

7.取非零元素的索引：torch.nonzero(input, out=None) → LongTensor

In [22]:
torch.nonzero(torch.tensor([1, 1, 1, 0, 1]))

tensor([[0],
        [1],
        [2],
        [4]])

In [23]:
torch.nonzero(torch.tensor([[0.6, 0.0, 0.0, 0.0],
                                [0.0, 0.4, 0.0, 0.0],
                                [0.0, 0.0, 1.2, 0.0],
                                [0.0, 0.0, 0.0,-0.4]]))

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

8.reshape张量：torch.reshape(input, shape) → Tensor  
元素数目和值相同，形状不同。  


In [25]:
a = torch.arange(4.)
torch.reshape(a, (2, 2))

tensor([[0., 1.],
        [2., 3.]])

In [26]:
b = torch.tensor([[0, 1], [2, 3]])
torch.reshape(b, (-1,))

tensor([0, 1, 2, 3])

9.分割矩阵：torch.split(tensor, split_size_or_sections, dim=0)  
split_size_or_sections：单个块的大小，或一个列表表示每个块的大小

10.去除维度为1的维度：torch.squeeze(input, dim=None, out=None) → Tensor  
结果和input共享内存，所以元素值一变全变  
dim：指定去除的维度，如果该维度不为1，则不操作

In [27]:
x = torch.zeros(2, 1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [29]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [30]:
y = torch.squeeze(x, 0) #该维度不为1
y.size()

torch.Size([2, 1, 2, 1, 2])

In [31]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

11.连接张量：torch.stack(seq, dim=0, out=None) → Tensor  
seq：要连接的张量序列  
张量的size要相同

12.转置：torch.t(input) → Tensor

In [32]:
x = torch.randn(2, 3)
x

tensor([[ 1.2165, -1.1617,  0.2792],
        [ 1.6782, -1.3492, -1.6946]])

In [33]:
torch.t(x)

tensor([[ 1.2165,  1.6782],
        [-1.1617, -1.3492],
        [ 0.2792, -1.6946]])

13.取出指定位置元素：torch.take(input, indices) → Tensor  
将input当做一维向量来处理  
indices：是在一维向量中的位置  
取出的向量和indices同长度

In [34]:
src = torch.tensor([[4, 3, 5],
                        [6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

14.转置：torch.transpose(input, dim0, dim1) → Tensor  
共享内存  
dim0:转置第一维  
dim1：转置第二维

In [35]:
x = torch.randn(2, 3)
x


tensor([[ 0.5855,  0.2253,  1.0154],
        [-0.3529, -0.7420,  0.2859]])

In [36]:
torch.transpose(x, 0, 1)

tensor([[ 0.5855, -0.3529],
        [ 0.2253, -0.7420],
        [ 1.0154,  0.2859]])

In [37]:
torch.transpose(x, 1, 0)

tensor([[ 0.5855, -0.3529],
        [ 0.2253, -0.7420],
        [ 1.0154,  0.2859]])

15.将tensor切片成元组：torch.unbind(tensor, dim=0) → seq

In [38]:
 torch.unbind(torch.tensor([[1, 2, 3],
                            [4, 5, 6],
                           [7, 8, 9]]))

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

16.增加维度：torch.unsqueeze(input, dim, out=None) → Tensor

In [39]:
x = torch.tensor([1, 2, 3, 4])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4]])

In [40]:
torch.unsqueeze(x, 1)

tensor([[1],
        [2],
        [3],
        [4]])

17.按条件从两个tensor中挑选元素组成新tensor：torch.where(condition, x, y) → Tensor  
condition：条件为True从x中选，否则从y中选  
x和y要是可以broadcastable的

In [42]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
x

tensor([[-0.4257,  0.7195],
        [-0.3652,  0.9774],
        [-1.1582, -0.1474]])

In [43]:
torch.where(x > 0, x, y)

tensor([[1.0000, 0.7195],
        [1.0000, 0.9774],
        [1.0000, 1.0000]])