数学操作  

1.绝对值：---------------------------------------torch.abs()  

2.反余弦 arccosine：-----------------------------torch.acos(）  

3.加法：-----------------------------------------torch.add()  

4.arcsine ：-------------------------------------torch.acos()  

5.arctangent:------------------------------------torch.atan()  

6.向上取整：-------------------------------------torch.ceil()

7.将元素值截取到范围内：-------------------------torch.clamp()  

8.cosine :---------------------------------------torch.cos()  

9.双曲余弦：-------------------------------------torch.cosh()  

10.除法：----------------------------------------torch.div()  

11.指数$e^{x}$：---------------------------------torch.exp()  

12.向下取整：------------------------------------torch.floor()  

13.取余数：--------------------------------------torch.fmod()  

14.取小数部分：--------------------------------- torch.frac()  

15.插值：----------------------------------------torch.lerp()

16.log(e):----------------------------------------torch.log()

17.log(10):--------------------------------------torch.log10()

18.log(2):---------------------------------------torch.log2()

19.乘法：----------------------------------------torch.mul()

20.正负数转换：-----------------------------------torch.neg()

21.指数：-------------------------------------------torch.pow()

22.倒数：----------------------------------------torch.reciprocal()

23.求余数：---------------------------------------torch.remainder()

24.四舍五入：-------------------------------------torch.round()

25.平方根的倒数：---------------------------------torch.rsqrt()

26.sigmoid：--------------------------------------torch.sigmoid()

27.元素符号：torch.sign()

28.sin:torch.sin()

29.双曲正弦sinh：torch.sinh()

30.平方根：torch.sqrt()

31.tan：torch.tan()

32.双曲正切tanh：torch.tanh()

33.截断整数值：torch.trunc()

In [40]:
import torch
import math

1.绝对值：torch.abs(input, out=None) → Tensor

In [2]:
torch.abs(torch.tensor([-1, -2, 3]))

tensor([1, 2, 3])

2.反余弦 arccosine：torch.acos(input, out=None) → Tensor

In [3]:
a = torch.randn(4)
a

tensor([-0.5204, -0.2498, -0.8906,  1.5236])

In [4]:
torch.acos(a)

tensor([2.1182, 1.8233, 2.6695,    nan])

3.加法：torch.add()

In [5]:
#torch.add(input, value, out=None)
a = torch.randn(4)
a

tensor([ 1.4758,  0.5580,  0.5706, -0.1011])

In [6]:
torch.add(a, 20)

tensor([21.4758, 20.5580, 20.5706, 19.8989])

In [7]:
a

tensor([ 1.4758,  0.5580,  0.5706, -0.1011])

In [8]:
#torch.add(input, value=1, other, out=None)
#out=input+value×other
a = torch.randn(4)
a

tensor([-0.1157,  0.4807,  0.4447, -0.0374])

In [9]:
b = torch.randn(4, 1)
b

tensor([[-0.1444],
        [-0.5747],
        [ 0.0590],
        [-0.7659]])

In [10]:
torch.add(a, 10, b)

tensor([[-1.5596, -0.9632, -0.9992, -1.4814],
        [-5.8626, -5.2662, -5.3022, -5.7843],
        [ 0.4741,  1.0705,  1.0345,  0.5523],
        [-7.7746, -7.1783, -7.2142, -7.6964]])

4.arcsine ：torch.asin(input, out=None) → Tensor

In [16]:
a = torch.randn(4)
a

tensor([-0.2673,  2.3617,  1.1891, -0.2189])

In [17]:
torch.asin(a)

tensor([-0.2706,     nan,     nan, -0.2207])

5.arctangent:torch.atan(input, out=None) → Tensor

In [18]:
a = torch.randn(4)
a


tensor([-0.4515, -2.0246, -0.9912,  1.5528])

In [19]:
torch.atan(a)

tensor([-0.4241, -1.1120, -0.7810,  0.9986])

6.向上取整：torch.ceil(input, out=None) → Tensor

In [21]:
a = torch.randn(4)
a

tensor([ 0.3203,  0.2253, -0.6711,  1.2606])

In [22]:
torch.ceil(a)

tensor([1., 1., -0., 2.])

7.将元素值截取到范围内：torch.clamp(input, min, max, out=None) → Tensor  
min：元素可取的最小值  
max：元素可取的最大值

In [23]:
a = torch.randn(4)
a

tensor([ 0.4924,  1.6887, -0.0874, -0.0056])

In [24]:
torch.clamp(a, min=-0.5, max=0.5)

tensor([ 0.4924,  0.5000, -0.0874, -0.0056])

In [25]:
#torch.clamp(input, *, min, out=None) → Tensor
a = torch.randn(4)
a

tensor([-0.1797, -0.1107,  1.9031,  0.8813])

In [26]:
torch.clamp(a, min=0.5)

tensor([0.5000, 0.5000, 1.9031, 0.8813])

In [27]:
#torch.clamp(input, *, max, out=None) → Tensor
a = torch.randn(4)
a

tensor([ 0.5207, -0.3032,  0.2954,  0.5074])

In [28]:
torch.clamp(a, max=0.5)

tensor([ 0.5000, -0.3032,  0.2954,  0.5000])

8. cosine :torch.cos(input, out=None) → Tensor

In [29]:
a = torch.randn(4)
a

tensor([ 1.6138, -0.3515, -0.3053,  0.0296])

In [30]:
torch.cos(a)

tensor([-0.0430,  0.9389,  0.9538,  0.9996])

9.双曲余弦：torch.cosh(input, out=None) → Tensor

In [32]:
a = torch.randn(4)
a

tensor([ 0.5483,  0.0630, -0.0056,  2.6376])

In [33]:
torch.cosh(a)

tensor([1.1541, 1.0020, 1.0000, 7.0256])

10.除法：torch.div()

In [34]:
a = torch.randn(5)
a

tensor([ 1.5104,  1.7043,  1.1862, -0.0617, -0.3137])

In [35]:
torch.div(a, 0.5)

tensor([ 3.0208,  3.4085,  2.3724, -0.1235, -0.6275])

In [36]:
#torch.div(input, other, out=None) → Tensor
a = torch.randn(4, 4)
a

tensor([[ 1.2676,  1.7474,  1.6725, -1.1404],
        [-0.0297, -1.8806,  0.0099,  0.1675],
        [-1.4077,  1.2384,  1.8159,  1.8818],
        [ 0.9189, -0.4780, -0.7641,  0.4924]])

In [37]:
b = torch.randn(4)
b

tensor([1.2764, 1.6828, 1.4207, 1.6418])

In [38]:
torch.div(a, b)

tensor([[ 0.9931,  1.0384,  1.1773, -0.6946],
        [-0.0233, -1.1175,  0.0070,  0.1020],
        [-1.1029,  0.7359,  1.2782,  1.1462],
        [ 0.7199, -0.2840, -0.5379,  0.2999]])

11.指数$e^{x}$：torch.exp(input, out=None) → Tensor	

In [41]:
torch.exp(torch.tensor([0, math.log(2.)]))

tensor([1., 2.])

12.向下取整：torch.floor(input, out=None) → Tensor

In [42]:
a = torch.randn(4)
a

tensor([-0.3935, -0.5670,  1.5182,  1.4599])

In [43]:
torch.floor(a)

tensor([-1., -1.,  1.,  1.])

13.取余数：torch.fmod(input, divisor, out=None) → Tensor  
input:被除数  
divisor：除数

In [44]:
torch.fmod(torch.tensor([-3., -2, -1, 1, 2, 3]), 2)

tensor([-1., -0., -1.,  1.,  0.,  1.])

In [45]:
torch.fmod(torch.tensor([1., 2, 3, 4, 5]), 1.5)

tensor([1.0000, 0.5000, 0.0000, 1.0000, 0.5000])

14.取小数部分： torch.frac(input, out=None) → Tensor

In [46]:
torch.frac(torch.tensor([1, 2.5, -3.2]))

tensor([ 0.0000,  0.5000, -0.2000])

15.插值：torch.lerp(start, end, weight, out=None)  
out =start +weight×(end −start )

In [47]:
start = torch.arange(1., 5.)
end = torch.empty(4).fill_(10)
start

tensor([1., 2., 3., 4.])

In [48]:
end

tensor([10., 10., 10., 10.])

In [49]:
torch.lerp(start, end, 0.5)

tensor([5.5000, 6.0000, 6.5000, 7.0000])

16.log(e):torch.log(input, out=None) → Tensor  
$y=log_{e}(x)$

In [52]:
a = torch.randn(5)
a

tensor([-0.2428, -1.0146, -0.0128,  1.0263,  0.2413])

In [53]:
torch.log(a)

tensor([    nan,     nan,     nan,  0.0260, -1.4216])

17.log(10):torch.log10(input, out=None) → Tensor  
    

In [55]:
a = torch.rand(5)
a

tensor([0.5535, 0.7960, 0.2566, 0.4568, 0.8052])

In [56]:
torch.log10(a)

tensor([-0.2569, -0.0991, -0.5907, -0.3403, -0.0941])

18.log(2):torch.log2(input, out=None) → Tensor

In [57]:
a = torch.rand(5)
a


tensor([0.1514, 0.6796, 0.0845, 0.1124, 0.6779])

In [58]:
torch.log2(a)

tensor([-2.7240, -0.5572, -3.5649, -3.1536, -0.5609])

19.乘法：torch.mul()

In [59]:
#torch.mul(input, value, out=None)
a = torch.randn(3)
a

tensor([ 0.2544,  0.7739, -0.1119])

In [60]:
torch.mul(a, 100)

tensor([ 25.4371,  77.3856, -11.1869])

In [61]:
#torch.mul(input, other, out=None)
a = torch.randn(4, 1)
a

tensor([[ 0.4716],
        [-0.9592],
        [-0.7340],
        [ 0.4113]])

In [62]:
b = torch.randn(1, 4)
b

tensor([[-0.6441,  0.3509, -1.2918,  0.3385]])

In [63]:
torch.mul(a, b)

tensor([[-0.3037,  0.1655, -0.6091,  0.1596],
        [ 0.6178, -0.3366,  1.2391, -0.3247],
        [ 0.4727, -0.2576,  0.9482, -0.2485],
        [-0.2649,  0.1443, -0.5313,  0.1392]])

20.正负数转换：torch.neg(input, out=None) → Tensor

In [64]:
a = torch.randn(5)
a

tensor([-1.1089,  0.2284,  0.7803, -1.0671, -0.1864])

In [65]:
torch.neg(a)

tensor([ 1.1089, -0.2284, -0.7803,  1.0671,  0.1864])

21.指数：torch.pow()

In [66]:
#torch.pow(input, exponent, out=None) → Tensor
a = torch.randn(4)
a

tensor([ 0.2444,  0.8809, -0.0627, -0.1779])

In [67]:
torch.pow(a, 2)

tensor([0.0597, 0.7759, 0.0039, 0.0316])

In [68]:
exp = torch.arange(1., 5.)

In [70]:
a = torch.arange(1., 5.)
a

tensor([1., 2., 3., 4.])

In [71]:
exp

tensor([1., 2., 3., 4.])

In [72]:
torch.pow(a, exp)

tensor([  1.,   4.,  27., 256.])

In [73]:
#torch.pow(base, input, out=None) → Tensor
exp = torch.arange(1., 5.)
base = 2
torch.pow(base, exp)

tensor([ 2.,  4.,  8., 16.])

22.倒数：torch.reciprocal(input, out=None) → Tensor

In [74]:
a = torch.randn(4)
a

tensor([-1.1675, -1.3311, -0.8863, -0.2122])

In [75]:
torch.reciprocal(a)


tensor([-0.8565, -0.7512, -1.1283, -4.7133])

23.求余数：torch.remainder(input, divisor, out=None) → Tensor  
余数符号和除数相同。

In [76]:
torch.remainder(torch.tensor([-3., -2, -1, 1, 2, 3]), 2)

tensor([1., 0., 1., 1., 0., 1.])

In [77]:
torch.remainder(torch.tensor([1., 2, 3, 4, 5]), 1.5)

tensor([1.0000, 0.5000, 0.0000, 1.0000, 0.5000])

24.四舍五入：torch.round(input, out=None) → Tensor

In [78]:
a = torch.randn(4)
a

tensor([0.6024, 0.1150, 0.5472, 0.8309])

In [79]:
torch.round(a)

tensor([1., 0., 1., 1.])

25.平方根的倒数：torch.rsqrt(input, out=None) → Tensor

In [80]:
a = torch.randn(4)
a

tensor([ 0.8757, -1.1404, -0.0678,  1.4442])

In [81]:
torch.rsqrt(a)

tensor([1.0686,    nan,    nan, 0.8321])

26.sigmoid：torch.sigmoid(input, out=None) → Tensor

In [82]:
a = torch.randn(4)
a

tensor([ 0.7940, -0.5334,  0.3950,  1.0220])

In [83]:
torch.sigmoid(a)

tensor([0.6887, 0.3697, 0.5975, 0.7354])

27.元素符号：torch.sign(input, out=None) → Tensor

In [84]:
a = torch.tensor([0.7, -1.2, 0., 2.3])
a

tensor([ 0.7000, -1.2000,  0.0000,  2.3000])

In [85]:
torch.sign(a)

tensor([ 1., -1.,  0.,  1.])

28.sin:torch.sin(input, out=None) → Tensor

In [86]:
a = torch.randn(4)
a


tensor([-1.3812,  1.0869,  1.5009, -0.7338])

In [87]:
torch.sin(a)

tensor([-0.9821,  0.8852,  0.9976, -0.6697])

29.双曲正弦sinh：torch.sinh(input, out=None) → Tensor

In [88]:
a = torch.randn(4)
a

tensor([-0.0325, -1.4042, -1.1385,  0.5686])

In [89]:
torch.sinh(a)

tensor([-0.0325, -1.9133, -1.4010,  0.5997])

30.平方根：torch.sqrt(input, out=None) → Tensor

In [90]:
a = torch.randn(4)
a

tensor([-1.6211,  1.1935, -0.2521, -0.8258])

In [91]:
torch.sqrt(a)

tensor([   nan, 1.0925,    nan,    nan])

31.tan：torch.tan(input, out=None) → Tensor

In [92]:
a = torch.randn(4)
a

tensor([-1.4846,  1.0323,  0.6190,  1.1188])

In [93]:
torch.tan(a)

tensor([-11.5747,   1.6739,   0.7124,   2.0599])

32.双曲正切tanh：torch.tanh(input, out=None) → Tensor

In [94]:
a = torch.randn(4)
a

tensor([ 3.2630,  0.5824, -0.5195,  0.9358])

In [95]:
torch.tanh(a)

tensor([ 0.9971,  0.5244, -0.4774,  0.7333])

33.截断整数值：torch.trunc(input, out=None) → Tensor

In [96]:
a = torch.randn(4)
a

tensor([-0.1470,  0.0739, -1.8700,  1.1015])

In [97]:
torch.trunc(a)

tensor([-0.,  0., -1.,  1.])